using Pixeltheory.Messaging;


[MessagingInterface]
public interface TestInterfacePixelScriptableObjectSingletonParameter
{
    void TestMethodPixelScriptableObjectSingletonParameter(TestClassPixelScriptableObjectSingle pixelScriptableObjectSingletonParameter);
}