using Pixeltheory.Messaging;


[MessagingInterface]
public interface TestInterfacePixelScriptableObjectSingletonParameter
{
    [MessagingTargetAll] public void TestMethodPixelScriptableObjectSingletonParameter(TestClassPixelScriptableObjectSingle pixelScriptableObjectSingletonParameter);
}